[package]
name = "jarvis_server_manager"
version = "1.2.1"
description = "J.A.R.V.I.S Server Manager"
authors = ["Armanc"]
edition = "2021"

[lib]
name = "jarvis_server_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2.3.6"
tauri-plugin-dialog = "2.7.3"
portable-pty = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
